require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/movie_directors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MovieDirector. As you add validations to MovieDirector, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MovieDirector.create! valid_attributes
      get movie_directors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      movie_director = MovieDirector.create! valid_attributes
      get movie_director_url(movie_director)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_movie_director_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      movie_director = MovieDirector.create! valid_attributes
      get edit_movie_director_url(movie_director)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MovieDirector" do
        expect {
          post movie_directors_url, params: { movie_director: valid_attributes }
        }.to change(MovieDirector, :count).by(1)
      end

      it "redirects to the created movie_director" do
        post movie_directors_url, params: { movie_director: valid_attributes }
        expect(response).to redirect_to(movie_director_url(MovieDirector.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MovieDirector" do
        expect {
          post movie_directors_url, params: { movie_director: invalid_attributes }
        }.to change(MovieDirector, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post movie_directors_url, params: { movie_director: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested movie_director" do
        movie_director = MovieDirector.create! valid_attributes
        patch movie_director_url(movie_director), params: { movie_director: new_attributes }
        movie_director.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the movie_director" do
        movie_director = MovieDirector.create! valid_attributes
        patch movie_director_url(movie_director), params: { movie_director: new_attributes }
        movie_director.reload
        expect(response).to redirect_to(movie_director_url(movie_director))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        movie_director = MovieDirector.create! valid_attributes
        patch movie_director_url(movie_director), params: { movie_director: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested movie_director" do
      movie_director = MovieDirector.create! valid_attributes
      expect {
        delete movie_director_url(movie_director)
      }.to change(MovieDirector, :count).by(-1)
    end

    it "redirects to the movie_directors list" do
      movie_director = MovieDirector.create! valid_attributes
      delete movie_director_url(movie_director)
      expect(response).to redirect_to(movie_directors_url)
    end
  end
end
